version: '3.8'

services:
  node-web-app:
    container_name: node-web-app
    build: .
    command: npm run dev
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=5050
      - HOST=0.0.0.0
    ports:
      - '35729:35729'